apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: firstapp
spec:
  containers:
  - name: mycontainer
    image: ricardocorrea/golang-example-kubernetes:0.1
    ports:
    - name: golang-port
      containerPort: 8080
