apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycontainer
        image: ricardocorrea/golang-example-kubernetes:0.2
        ports:
        - name: golang-port
          containerPort: 8080
